version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "mostafaalagamy"
    labels:
      - "dependencies"
      - "android"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    reviewers:
      - "mostafaalagamy"
    labels:
      - "ci"
      - "automated"
