name: Build ARM64 Debug APK

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/build_arm64_debug.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Install SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-36" "build-tools;36.0.0"
          yes | sdkmanager --licenses

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true
          cache-cleanup: on-success

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate debug.keystore
        run: |
          mkdir -p ~/.android
          keytool -genkey -v \
            -keystore ~/.android/debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Build ARM64 Debug APK
        run: ./gradlew --no-configuration-cache --console=plain clean assembleArm64Debug --warning-mode summary
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_SECRET: ${{ secrets.LASTFM_SECRET }}

      - name: Upload ARM64 Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-debug-${{ github.run_number }}
          path: app/build/outputs/apk/arm64/debug/*.apk
          
      - name: Get APK info
        run: |
          echo "APK built successfully!"
          ls -lh app/build/outputs/apk/arm64/debug/

