name: Move Java files to Kotlin directories (multiple modules)

on:
  workflow_dispatch:
  push:
    branches: [ '**' ]

jobs:
  move-multiple-java-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move folders
        run: |
          # Kizzy
          if [ -d "kizzy/src/main/java/com/my/kizzy" ]; then
            mkdir -p kizzy/src/main/kotlin/com/my
            git mv kizzy/src/main/java/com/my/kizzy kizzy/src/main/kotlin/com/my/
          fi

          # Innertube
          if [ -d "innertube/src/main/java/com/metrolist/innertube" ]; then
            mkdir -p innertube/src/main/kotlin/com/metrolist
            git mv innertube/src/main/java/com/metrolist/innertube innertube/src/main/kotlin/com/metrolist/
          fi

          # Kugou
          if [ -d "kugou/src/main/java/com/metrolist/kugou" ]; then
            mkdir -p kugou/src/main/kotlin/com/metrolist
            git mv kugou/src/main/java/com/metrolist/kugou kugou/src/main/kotlin/com/metrolist/
          fi

          # Lrclib
          if [ -d "lrclib/src/main/java/com/metrolist/lrclib" ]; then
            mkdir -p lrclib/src/main/kotlin/com/metrolist
            git mv lrclib/src/main/java/com/metrolist/lrclib lrclib/src/main/kotlin/com/metrolist/
          fi

          # Clean up java folders if empty
          find . -type d -path "*/src/main/java" -empty -exec rm -r {} +

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Moved kizzy, innertube, kugou, lrclib from java to kotlin folders"
          git push
