name: Move Java to Kotlin Folder

on:
  workflow_dispatch:

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Move files from java to kotlin
        run: |
          mkdir -p app/src/main/kotlin/com/metrolist/music
          mv app/src/main/java/com/metrolist/music/* app/src/main/kotlin/com/metrolist/music/
          rm -r app/src/main/java/com/metrolist/music

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Moved music files from java to kotlin folder"
          git push
